eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8084
spring:
  application:
    name: spring-cloud-zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: spring-cloud-consumer
    api-b:
      path: /api-b/**
      serviceId: spring-cloud-provider
      