spring:
  application:
    name: spring-cloud-config-server
  profiles:
## 开启本地配置
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xupeng001/config-repo
          search-paths: repo
          username: 
          password: 

server:
  port: 1201


